# Generated by Django 2.0.2 on 2018-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180306_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='name of shop'),
        ),
    ]
