# Generated by Django 2.0.2 on 2018-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_remove_user_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shops.Shop'),
        ),
    ]
