# Generated by Django 2.0.2 on 2018-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_user_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='users', to='shops.Shop'),
        ),
    ]
